title: 'Book Light Editorial'
default_lang: en
author:
  name: 'Carly Hayward'
  email: carly@booklighteditorial.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Book Light Editorial offers freelance developmental and copy editing services and writing tips for indie authors and publishing authors'
  author: 'Carly Bornstein-Hayward'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /about: /team
  /recommendations: /testimonials
blog:
  route: /blog
footer:
  links:
    -
      text: Services
      href: /services
    -
      text: Contact
      href: /contact
    -
      text: Privacy Policy
      href: /
